"""reviews/2026-09-24-bot-vs-cells.md quotes the live bot gate; this holds it to it.

The note's predicates block is generated by scripts/bot_vs_cells.py from
config, and each line of it is ALSO pinned here against the behaviour of the
code it describes -- so the note goes stale loudly, not silently:
  * change a bot constant and the committed block no longer equals what the
    script would print;
  * change what the gate reads (grade_raw, the plan's entry, a missing
    level_tf) and the behavioural pin for that line goes red.
When one fails after a deliberate rule change, re-run the script and commit
the regenerated note in the same PR -- that is the point of the pin.

The classifier and the freshness mirror are tested on synthetic rows only:
journal/ is live data and never a test fixture.
"""

from __future__ import annotations

import datetime as dt
import importlib.util
import pathlib
import re

import pytest

from scanner import config
from scanner.broker import vivek_bot as vb
from scanner.broker import vivek_run as vr

ROOT = pathlib.Path(__file__).resolve().parents[1]
NOTE = (ROOT / "reviews" / "2026-09-24-bot-vs-cells.md").read_text(encoding="utf-8")
_spec = importlib.util.spec_from_file_location("bot_vs_cells", ROOT / "scripts" / "bot_vs_cells.py")
bvc = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(bvc)


def _block() -> dict:
    m = re.search(r"The predicates, as the code reads today.*?```text\n(.*?)```", NOTE, re.S)
    assert m, "the note lost its predicates block"
    return {k.strip(): v.strip() for k, v in
            (line.split("=", 1) for line in m.group(1).strip().splitlines())}


# -- the note's block is what the script prints from today's config --------

def test_the_committed_block_is_what_the_config_says_today():
    assert bvc.predicates_block() in NOTE, (
        "a bot constant moved: re-run scripts/bot_vs_cells.py and commit the note")


def test_the_first_line_is_the_verdict():
    first = NOTE.splitlines()[0]
    assert re.match(r"\*\*Gate matches four-cell: [YN]\. Open positions in-cell: \d+/\d+\*\*", first)


# -- and every line of the block is true of the code -----------------------

def _row(plan_entry=100.0, stop=90.0, grade_raw="A+", grade="A+", tf="1W", trigger="reclaim",
         direction="LONG", name="Operating Co", sector="Industrials"):
    plan = {"entry": plan_entry, "stop": stop, "armed": True, "entry_trigger": trigger,
            "rr": 2.0, "scale": [0.25, 0.5, 0.15]}
    risk = abs(plan_entry - stop)
    sign = 1 if direction == "LONG" else -1
    plan.update(tp1=plan_entry + sign * risk, tp2=plan_entry + sign * 2 * risk,
                tp3=plan_entry + sign * 3 * risk)
    return {"symbol": "X", "name": name, "sector": sector, "dir": direction, "grade": grade,
            "grade_raw": grade_raw, "plans": {tf: plan}, "data_age_days": 0}


def test_direction_long_only():
    assert _block()["direction"] == "long only" and config.VIVEK_BOT_ALLOW_SHORTS is False
    assert vb.evaluate_setup(_row(direction="SHORT", stop=110.0))["code"] == "shorts_disabled"


def test_grades_and_their_source_is_grade_raw():
    b = _block()
    assert tuple(g.strip() for g in b["grades"].split(",")) == config.VIVEK_BOT_GRADES
    assert b["grade_source"] == "grade_raw"
    # the displayed grade says A+, the raw grade says B+: the gate reads raw
    assert vb.evaluate_setup(_row(grade="A+", grade_raw="B+"))["code"] == "grade_excluded"
    assert vb.evaluate_setup(_row(grade="B+", grade_raw="A"))["take"] is True


def test_the_cells_and_the_walk_order():
    b = _block()
    cells = [c.strip() for c in b["cells"].split(",")]
    assert cells == [f"{tf} {et}" for tf, ets in config.VIVEK_BOT_ENTRY_CELLS.items() for et in ets]
    assert [t.strip() for t in b["cell_walk"].split(">")] == list(config.VIVEK_BOT_ENTRY_CELLS)
    for cell in cells:
        tf, et = cell.split()
        assert vb.evaluate_setup(_row(tf=tf, trigger=et))["take"] is True, cell
    for tf, et in (("1D", "reclaim"), ("3D", "break"), ("1W", "retest")):
        assert vb.evaluate_setup(_row(tf=tf, trigger=et))["code"] == "no_cell_plan", (tf, et)


def test_the_level_gate_and_a_missing_level_is_dropped():
    b = _block()
    assert tuple(x.strip() for x in b["level_tf"].split(",")) == config.VIVEK_BOT_LEVEL_TF_ALLOW
    assert b["level_tf_missing"] == "dropped"
    kept, dropped = vr._apply_level_gate([{"level_tf": "weekly"}, {"level_tf": "3d"},
                                          {"level_tf": "h4"}, {"level_tf": None}, {}])
    assert [r["level_tf"] for r in kept] == ["weekly", "3d"] and dropped == 3


def test_the_stop_band_is_read_off_the_plan_entry_then_the_fill():
    b = _block()
    assert float(b["max_stop_pct"]) == config.VIVEK_BOT_MAX_STOP_PCT
    assert float(b["min_stop_pct"]) == config.VIVEK_BOT_MIN_STOP_PCT
    assert b["stop_basis"] == "plan entry, then fill"
    cap = config.VIVEK_BOT_MAX_STOP_PCT
    assert vb.evaluate_setup(_row(stop=100.0 - (cap - 1)))["take"] is True
    assert vb.evaluate_setup(_row(stop=100.0 - (cap + 1)))["code"] == "wide_stop"


def _ticket(stop, fill):
    return {"symbol": "X", "name": "X", "sector": "", "direction": "long", "grade": "A+",
            "entry_type": "reclaim", "entry_type_label": "x", "timeframe": "1W",
            "entry": 100.0, "stop": stop, "tp1": fill * 1.3, "tp2": fill * 1.6, "tp3": fill * 2,
            "scale": [0.25, 0.5, 0.15], "trigger_bar": None, "leverage_target": 5.0,
            "units": 1.0, "notional": 5000.0, "leverage": 1.0, "risk_pct": 0.1, "risk_usd": 1.0}


def test_the_cap_is_re_read_at_the_fill():
    """The finding in the note, closed by section 5's first patch (applied
    2026-09-24): a plan inside the cap at the signal close whose fill moved
    far enough to put the stop outside it is not booked."""
    cap = config.VIVEK_BOT_MAX_STOP_PCT
    stop = 100.0 - (cap - 2)                           # inside the cap at the plan entry
    wide = stop / (1 - (cap + 2) / 100.0)              # outside it at the fill
    assert vr._ticket_to_position({"plan": _ticket(stop, wide)}, wide, "nasdaq", "2026-09-24") is None
    near = stop / (1 - (cap - 1) / 100.0)              # moved, still inside
    pos = vr._ticket_to_position({"plan": _ticket(stop, near)}, near, "nasdaq", "2026-09-24")
    assert pos is not None and pos["risk"] / pos["entry"] * 100 <= cap


def test_the_other_gate_constants():
    b = _block()
    assert float(b["min_rr"]) == config.VIVEK_BOT_MIN_RR
    assert b["exclude_funds"] == str(config.VIVEK_BOT_EXCLUDE_FUNDS)
    assert int(b["max_per_sector"]) == config.VIVEK_BOT_MAX_PER_SECTOR
    assert int(b["max_open_total"]) == config.VIVEK_BOT_MAX_OPEN_TOTAL
    assert int(b["max_hold_days"]) == config.VIVEK_BOT_MAX_HOLD_DAYS
    assert vb.evaluate_setup(_row(name="Some Property REIT"))["code"] == "fund_reit"


# -- the classifier --------------------------------------------------------

def _pos(**kw):
    base = {"id": "X:long:1W:2026-09-22", "symbol": "X", "name": "Operating Co",
            "sector": "Industrials", "direction": "long", "grade": "A+", "timeframe": "1W",
            "entry_type": "reclaim", "level_tf": "weekly", "entry": 100.0, "risk": 20.0,
            "signal_entry": 100.0, "entry_date": "2026-08-10", "_market": "nasdaq",
            "_side": "open"}
    base.update(kw)
    return base


def test_an_in_cell_position():
    c = bvc.classify(_pos())
    assert c["cls"] == "in" and c["why"] == [] and c["plan_stop"] == pytest.approx(20.0)


@pytest.mark.parametrize("kw,reason", [
    ({"timeframe": "1D"}, "1D reclaim is not a cell"),
    ({"level_tf": "h4"}, "h4 level"),
    ({"risk": 30.0}, "stop 30.0%"),
    ({"direction": "short"}, "short"),
    ({"name": "Some Index ETF"}, "fund/REIT"),
])
def test_each_failing_predicate_is_named(kw, reason):
    c = bvc.classify(_pos(**kw))
    assert c["cls"] == "out" and reason in c["why"], c


def test_a_missing_level_is_unknown_not_out():
    c = bvc.classify(_pos(level_tf=None))
    assert c["cls"] == "unknown" and c["unknown"] == ["level_tf"]


def test_the_grade_comes_from_the_scan_once_A_is_takeable():
    """plan_trade stamps "A+" on every ticket, so after 2026-09-21 the book's
    grade cannot be trusted; the scan row's grade_raw can."""
    late = _pos(entry_date=bvc.A_TAKEABLE_SINCE)
    assert bvc.classify(late)["unknown"] == ["grade"]
    c = bvc.classify(late, {"grade_raw": "A"})
    assert c["cls"] == "in" and c["grade"] == "A" and c["grade_src"] == "scan grade_raw"
    assert bvc.classify(late, {"grade_raw": "B+"})["why"] == ["grade B+"]
    old = bvc.classify(_pos(entry_date="2026-07-01"))
    assert old["cls"] == "unknown" and old["unknown"] == ["grade source"]


def test_the_stop_is_read_at_the_plan_and_the_fill_is_flagged_separately():
    # plan stop 80 on a 100 signal = 20% (gate passes); filled at 110 = 27.3%
    c = bvc.classify(_pos(entry=110.0, risk=30.0, signal_entry=100.0))
    assert c["cls"] == "in" and c["plan_stop"] == pytest.approx(20.0)
    assert c["fill_over_cap"] and c["fill_stop"] == pytest.approx(30 / 110 * 100)


# -- freshness mirrors the deck's session + 2h rule ------------------------

def test_session_staleness_mirrors_the_deck():
    utc = dt.timezone.utc
    now = dt.datetime(2026, 9, 24, 3, 0, tzinfo=utc)          # 13:00 AEST Thu: open + 3h
    assert bvc.session_staleness("2026-09-24T08:11:50+10:00", "asx", now)["stale"] is True
    assert bvc.session_staleness("2026-09-24T11:07:00+10:00", "asx", now)["stale"] is False
    early = dt.datetime(2026, 9, 24, 0, 42, tzinfo=utc)       # 10:42 AEST: open + 42m
    v = bvc.session_staleness("2026-09-24T08:11:50+10:00", "asx", early)
    assert v["stale"] is False and v["edge"] == "close"
    sat = dt.datetime(2026, 9, 26, 12, 0, tzinfo=utc)         # weekend: Friday's close rules
    assert bvc.session_staleness("2026-09-25T16:30:00-04:00", "nasdaq", sat)["stale"] is False
    assert bvc.session_staleness("2026-09-25T15:00:00-04:00", "nasdaq", sat)["stale"] is True
    assert bvc.session_staleness("2026-09-24T00:00:00+00:00", "crypto", early)["stale"] is False
    assert bvc.session_staleness("2026-09-23T20:00:00+00:00", "crypto", early)["stale"] is True
    assert bvc.session_staleness("not a time", "asx", now)["stale"] is True


def test_prose_sections_and_the_write_fence():
    assert bvc.read_prose("@@ a\nx\ny\n@@ b\n\nz\n") == {"a": "x\ny", "b": "z"}
    hunk = "@@ -650,6 +650,12 @@ def _ticket_to_position(out: dict):"
    assert bvc.read_prose(f"@@ patch\n```diff\n{hunk}\n+x\n```\n")["patch"].count(hunk) == 1
    assert "```diff" in NOTE and "@@ -650," in NOTE and "decision[\"grade\"]" in NOTE, (
        "the section-5 patches must be in the note whole")
    src = (ROOT / "scripts" / "bot_vs_cells.py").read_text(encoding="utf-8")
    assert "git add" not in src and "write_text" not in src
    assert src.count("atomic_write(") == 2, "writes only the note and the entry-scan cache"
    git = set(re.findall(r'\["git", "(\w+)"', src))
    assert git == {"log", "show"}, git
