"""Risk management constants — all sourced from scanner/config.py."""
from scanner.config import (
    DEMOTE_LOW_RR,
    MIN_TRADEABLE_RR,
    LOW_RR_THRESHOLD,
    TRADEABLE_GRADES,
    WATCH_GRADES,
    POSITION_SIZE_USD,
    BROKERAGE_EACH_WAY,
    MAX_POSITIONS_LONG,
    MAX_POSITIONS_SHORT,
    SCALP_MAX_TRADES_PER_DAY,
    SCALP_MAX_DAILY_LOSS,
    SCALP_LEVERAGE,
    SCALP_POSITION_SIZE,
    SCALP_FILL_SLIPPAGE_PCT,
    SCALP_MAX_PER_GROUP,
    SCALP_CORRELATION_GROUPS,
    BYBIT_MIN_QTY_USD,
)

__all__ = [
    "DEMOTE_LOW_RR", "MIN_TRADEABLE_RR", "LOW_RR_THRESHOLD",
    "TRADEABLE_GRADES", "WATCH_GRADES",
    "POSITION_SIZE_USD", "BROKERAGE_EACH_WAY",
    "MAX_POSITIONS_LONG", "MAX_POSITIONS_SHORT",
    "SCALP_MAX_TRADES_PER_DAY", "SCALP_MAX_DAILY_LOSS", "SCALP_LEVERAGE",
    "SCALP_POSITION_SIZE", "SCALP_FILL_SLIPPAGE_PCT",
    "SCALP_MAX_PER_GROUP", "SCALP_CORRELATION_GROUPS",
    "BYBIT_MIN_QTY_USD",
]
